spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: demo-client
            client-secret: 5087112e-b819-40b6-8e1f-8e2558d925d4
            scope: openid, profile, email, roles
        provider:
          keycloak:
            issuer-uri: http://localhost:8181/auth/realms/SecurityDemo

logging:
  level:
    org.springframework.security.*: trace

